#!/usr/bin/env python3
"""
Generate CATALOG.md from the failure-mode YAML files.

Reads every .yaml file in failure-modes/, validates it against the required
schema fields, and writes a single readable CATALOG.md grouped by category.

Usage:
    python scripts/generate_catalog.py

Requires: pyyaml  (pip install pyyaml)
"""

import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("Missing dependency: pyyaml. Install with `pip install pyyaml`.")

ROOT = Path(__file__).resolve().parent.parent
FAILURE_DIR = ROOT / "failure-modes"
OUTPUT = ROOT / "CATALOG.md"

REQUIRED_FIELDS = [
    "id", "name", "category", "summary", "cause",
    "user_experience", "stakes_context", "detection",
    "mitigation", "example",
]

CATEGORY_ORDER = [
    "accuracy", "consistency", "calibration",
    "safety", "reliability", "interaction",
]

CATEGORY_TITLES = {
    "accuracy": "Accuracy",
    "consistency": "Consistency",
    "calibration": "Calibration",
    "safety": "Safety",
    "reliability": "Reliability",
    "interaction": "Interaction",
}


def load_failure_modes():
    modes = []
    for path in sorted(FAILURE_DIR.glob("*.yaml")):
        with open(path, "r", encoding="utf-8") as f:
            data = yaml.safe_load(f)
        missing = [field for field in REQUIRED_FIELDS if field not in data]
        if missing:
            sys.exit(f"{path.name} is missing required fields: {', '.join(missing)}")
        modes.append(data)
    return modes


def render_list(items):
    return "\n".join(f"- {str(item).strip()}" for item in items)


def render_mode(mode):
    sc = mode["stakes_context"]
    lines = [
        f"### {mode['name']}",
        "",
        f"`{mode['id']}` · **Category:** {CATEGORY_TITLES.get(mode['category'], mode['category'])}",
        "",
        f"{mode['summary'].strip()}",
        "",
        "**Cause**",
        "",
        mode["cause"].strip(),
        "",
        "**How users experience it**",
        "",
        mode["user_experience"].strip(),
        "",
        "**Where it matters**",
        "",
        f"- **High stakes:** {sc.get('high', '').strip()}",
        f"- **Low stakes:** {sc.get('low', '').strip()}",
        "",
        "**Detection**",
        "",
        render_list(mode["detection"]),
        "",
        "**Mitigation**",
        "",
        render_list(mode["mitigation"]),
        "",
        "**Example**",
        "",
        f"> {mode['example'].strip()}",
    ]
    if mode.get("related"):
        related = ", ".join(f"`{r}`" for r in mode["related"])
        lines += ["", f"**Related:** {related}"]
    return "\n".join(lines)


def build_catalog(modes):
    by_cat = {}
    for m in modes:
        by_cat.setdefault(m["category"], []).append(m)

    out = [
        "# AI Failure Mode Catalog",
        "",
        "> Auto-generated from the YAML files in `failure-modes/`. "
        "Do not edit this file by hand — edit the source YAML and run "
        "`python scripts/generate_catalog.py`.",
        "",
        f"**{len(modes)} failure modes** across "
        f"{len([c for c in CATEGORY_ORDER if c in by_cat])} categories.",
        "",
        "## Contents",
        "",
    ]

    for cat in CATEGORY_ORDER:
        if cat not in by_cat:
            continue
        out.append(f"- **{CATEGORY_TITLES[cat]}**")
        for m in by_cat[cat]:
            anchor = m["name"].lower().replace(" / ", "-").replace(" ", "-")
            out.append(f"  - [{m['name']}](#{anchor})")
    out.append("")

    for cat in CATEGORY_ORDER:
        if cat not in by_cat:
            continue
        out.append(f"## {CATEGORY_TITLES[cat]}")
        out.append("")
        for m in by_cat[cat]:
            out.append(render_mode(m))
            out.append("")
            out.append("---")
            out.append("")

    return "\n".join(out).rstrip() + "\n"


def main():
    modes = load_failure_modes()
    catalog = build_catalog(modes)
    OUTPUT.write_text(catalog, encoding="utf-8")
    print(f"Wrote {OUTPUT.relative_to(ROOT)} ({len(modes)} failure modes).")


if __name__ == "__main__":
    main()
